### ISSUE TITLE
Upload Image to bing return 400

### ISSUE THREAD

**Issue by andresayac** [Richard-Weiss/node-chatgpt-api#13]
**Describe the bug**
I see that if we do not send SRCHHPGUSR=HV= with a timestamp it returns a 400. In my case I don't know if it is happening to others

**To Reproduce**
1. Upload an image to bing

**Expected behavior**
Upload an image to google to return the corresponding blob

**Screenshots**
![image](https://github.com/Richard-Weiss/node-chatgpt-api/assets/16548795/983d9306-a678-486d-bd67-1341dd83dab2)

**Node.js version (please complete the following information):**
 - OS: Windows and Ubuntu
 - Version Node.js v18.16.0

**Package version (please complete the following information):**
 - Last version

**Comment by Richard-Weiss** [comment]
@andresayac
Does your cookie include the MUID, _U and _RwBf values?
Because recently you need these three instead of just the _U cookie for any requests.
I tested it and I get a 200 but no processBlobId, so there seems to be an issue in general.
I don't use the image recognition at all so I have to investigate some more.

**Comment by andresayac** [comment]
@Richard-Weiss 

my cookie only includes _U, that's why what I was telling you when uploading the image, I went with each item in the cookie until I reached those two to be able to upload the image,

The way I recreated it was to go to bing when it makes that request, copy it into a language I saw that it worked so I shortened the cookie

**Comment by andresayac** [comment]
I'm going to include them to see how curious that is. Hehe, if I currently only use it with _U, and I don't use a plugin, I'm going to gossip.  By the way, very good work.

**Comment by andresayac** [comment]
With the latest changes it works perfectly for me, thank you very much @Richard-Weiss
