### ISSUE TITLE
Bing: Add Suno.ai plugin

### ISSUE THREAD

**Issue by Richard-Weiss** [Richard-Weiss/node-chatgpt-api#3]
### Discussed in https://github.com/Richard-Weiss/node-chatgpt-api/discussions/2

<div type='discussions-op-text'>

<sup>Originally posted by **vaibhavard** January  4, 2024</sup>
Support for SunoAI plugin already available in copilot Microsoft (allows you to compose your own music using bing chat)</div>

**Comment by Richard-Weiss** [comment]
Necessary steps:
Websocket message:
"contentOrigin": "suno",
"hiddenText": "RequestId=d06be08f-a44b-451d-a4e0-68ff1b489cab",

GET Request with Cookie header:
https://www.bing.com/videos/music?vdpp=suno&kseed=7500&SFX=2&q=&iframeid=404d53c5-d518-4f19-887e-a5eb989a62b1&requestid=d06be08f-a44b-451d-a4e0-68ff1b489cab

in HTML Response:
<div id="b_data">
data-pageconfig
skey=

Poll https://www.bing.com/videos/api/custom/music?skey=6kGq0s8OSv5oYAkkZbj61qjD-4DO0ORKywbmp9OVN3g&requestid=d06be08f-a44b-451d-a4e0-68ff1b489cab until status: complete in response.

Get video_url and just return it. Looks like this: https://cdn1.suno.ai/d06be08f-a44b-451d-a4e0-68ff1b489cab.mp4

**Comment by Richard-Weiss** [comment]
@vaibhavard
Small update, I haven't forgotten about this.  
I pushed a preliminary commit to the [3_suno-plugin](https://github.com/Richard-Weiss/node-chatgpt-api/tree/3_suno-plugin) branch, but it's not working yet.  
Everything seems to work, except for the media from Suno not being uploaded to the media server of Microsoft.  
I don't know yet what's missing, but maybe someone else has an idea or wants to build upon this.  
I think I'll add the Suno link instead, should work that way.

**Comment by andresayac** [comment]
I was looking at what you say, I see that you build the link, this is enough to download the file, I don't know when you mean that they are not loaded in the Microsoft one, we can still have access to the audio directly to download and share
https://th.bing.com/th?&id=OIG1.a_3feadbe393344b32a89f1137a1ce6fb8&w=0&h=0&c=7&pid=1.7&rs=1

**Comment by Richard-Weiss** [comment]
@andresayac
It returned a 404 for all three links when I tried it, but I'm glad it works. The suno CDN link will always work.
