### ISSUE TITLE
GPT-4 Turbo No longer works .

### ISSUE THREAD

**Issue by vaibhavard** [Richard-Weiss/node-chatgpt-api#6]
**Describe the bug**
Earlier , Passing gpt-4 turbo yielded fast results , and the results were also similar to gpt-4-turbo writing style.
Now even when we pass gpt-4 turbo in model args  , results generated are not of gpt-4 turbo but of bing precise.
This can be verified by slower output and incorrect ans to specific questions that only gpt-4 turbo can solve.

**possible reason**
It may be because microsoft has introduced copilot pro or removed gpt-4 turbo from free tier.

**probable fixes**
Maybe model name has changes such as dlgpt-4-turbo?

**Comment by vaibhavard** [comment]
How to verify if the model gpt4t is actually gpt4t

**Comment by vaibhavard** [comment]
Maybe the model name has changed ?

**Comment by Richard-Weiss** [comment]
@vaibhavard 
Could be anything. I don't have Turbo for the vanilla implementation, so I don't know what changed.
Just have to wait for it to flight again or someone else finding the optionSet.

**Comment by PeronGH** [comment]
> How to verify if the model gpt4t is actually gpt4t

My method is to ask it "What is Bun runtime", because Bun is so new that only GPT-4 Turbo knows. And none of `"gpt4t", "dlgpt4t", "gpt4tmnc"` is working right now.

**Comment by PeronGH** [comment]
I subscribed to Copilot Pro to investigate the issue and found that the option is still functional; however, it requires Copilot Pro. Therefore, free users no longer have access to GPT-4 Turbo, even if they select the correct option in the settings.

**Comment by Richard-Weiss** [comment]
@PeronGH 
Thanks for confirming.  
I'll add it to the README so it won't lead to confusion.

**Comment by Richard-Weiss** [comment]
I'll leave this open until Turbo can be replicated on a free account or with the same optionSet not reproduced with definite proof.

**Comment by vaibhavard** [comment]
That"s Great! I am not able to make gpt-4-turbo work with a work account as well (Yet)

**Comment by Richard-Weiss** [comment]
@PeronGH @vaibhavard 
I've added Turbo support in #12 now.
However, you need to use a cookie that has Copilot Pro for it to work.
