### ISSUE TITLE
Support GPT Personas

### ISSUE THREAD

**Issue by Richard-Weiss** [Richard-Weiss/node-chatgpt-api#7]
Since GPTs or internally called "Personas" are in preview I'll add an option for them.
Currently I have access to and will add:

- Designer
- Vacation planning helper (Vacation Planner)
- Cooking helper (Cooking assistant)
- Fitness helper (Fitness trainer)

Using JB mode and a new system message will override the Persona.

**Comment by vaibhavard** [comment]
This will be accessible for free or only via copilot pro ?

**Comment by Richard-Weiss** [comment]
@vaibhavard You can use it now already. I think it's just a specific system message for each one.
